In [58]:
import numpy as np

# Basic Array Creation

In [16]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [17]:
#It is list Mixed Data types Are Allowed
lst = [1,2,3 , "Mazhar" , 20.5]
lst

[1, 2, 3, 'Mazhar', 20.5]

In [18]:
#Same datatype only allowed (Mixed list converted into single string datatype)
np.array(lst)

array(['1', '2', '3', 'Mazhar', '20.5'], dtype='<U32')

In [19]:
lst = [[1,2,3], [4,5,6] , [7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
#Converted list into array
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Genration Function

In [21]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr = np.arange(1,5,2)
arr

array([1, 3])

In [25]:
arr = np.zeros(8)
arr

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
arr = np.zeros((3,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [38]:
arr = np.ones((1,2))
arr

array([[1., 1.]])

In [34]:
arr = np.linspace(1,10,2)
arr

array([ 1., 10.])

In [35]:
arr = np.linspace(1,10,4)
arr

array([ 1.,  4.,  7., 10.])

In [36]:
arr = np.linspace(1,10,10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Random Genration Function

In [39]:
 np.random.rand(5)

array([0.72780846, 0.19156811, 0.38979402, 0.08949739, 0.56466183])

In [40]:
np.random.rand(10)

array([0.61621441, 0.74427854, 0.81651436, 0.20347694, 0.82915008,
       0.36610341, 0.63879388, 0.89159555, 0.08334437, 0.64835648])

In [41]:
np.random.randn(10)

array([ 0.29578945, -1.28808986, -1.36746468, -0.39944605, -1.60515804,
       -1.48355942, -0.01759699, -1.19330267, -0.83292808, -0.38004428])

In [42]:
np.random.randint(10)

9

In [44]:
np.random.randint(10,100,6)

array([91, 52, 27, 92, 93, 52])

# Array Attributes

In [47]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr.shape

(3, 3)

In [50]:
arr.size

9

In [51]:
arr.dtype

dtype('int64')

# Array Methods

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr.min()

np.int64(1)

In [55]:
arr.max()

np.int64(9)

In [56]:
arr.sum()

np.int64(45)

In [60]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [61]:
np.sum(arr,axis =1)

array([ 6, 15, 24])

In [62]:
arr.mean()

np.float64(5.0)

In [63]:
arr.std()

np.float64(2.581988897471611)

In [64]:
arr.argmax()

np.int64(8)

In [65]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

In [66]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [71]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])